from setuptools import setup, find_packages

setup(
    name="ragtime_llm",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "numpy",
        "torch",
        "pytube",
        "youtube_transcript_api",
        "whisper",
        "sentence-transformers",
        "gradio",
        "openai",
        "llama-cpp-python",
        "opencv-python",
        "Pillow",
        "tiktoken",
        "moviepy",
        "pytest",
        "pytest-asyncio",
        "pytest-cov"
    ],
    python_requires=">=3.8",
    author="Your Name",
    author_email="your.email@example.com",
    description="A Joplin-inspired RAG system for YouTube videos with GPU acceleration",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/ragtime-llm",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
) 